### ISSUE TITLE
פרוצדורות הכנסה

### ISSUE THREAD

**Issue by shaykos** [ruppinCgroup69/InventoryEyeProj#1]
יש ליצור פרוצדורות הכנסה לכל הטבלאות

**Comment by ruppinCgroup69** [comment]
Users:
everything but [UserId] (pk)

Comments:
everything but [PostId], [Id] (pk)

CommentScore:
everything but [CommentId], [PublishedBy], [RatedBy] (pk)
How to create a condition that if we have rated this comment once it is not possible to submit a new rating for it?

Posts:
everything but [Id] (pk)

Did not create Insert methode for Category ,StockLevel, Store, StoreCategory,UserRoles,Weigths tables.

**Comment by shaykos** [comment]
יש ליצור פרוצדורות הכנסה לשאר הטבלאות שנשארו
