### ISSUE TITLE
פרוצדורות עדכון

### ISSUE THREAD

**Issue by shaykos** [ruppinCgroup69/InventoryEyeProj#3]
יש ליצור פרוצדורות עדכון לכל טבלה. 
שימו לב לא לשכוח את פקודת where

**Comment by ruppinCgroup69** [comment]
We created update procedures for the following tables:
Update Users - How to allow the email to be updated if the WHERE is according to it?
Update Comments- We did not define the variables UserId, CreatedAt in the SET command 
Update Post- We did not define the variables UserId, CreatedAt in the SET command 

Update Comment Score- We haven't created the procedure yet. According to which fields is the update required? 
COMMENTID,RATEDBY,PUBLISHDBY are primary keys so they are not declared in the procedure
